# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WebExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WebExample

  target 'WebExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WebExampleP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WebExampleP

   pod 'IBMTealeafDebug'

end
